config/routes.rb
Rails.application.routes.draw do

  root to: "site#index"

  devise_for :users, :controllers => { :registrations => "registrations" }

  get "/admin" => "users#index"

  resources :site, :only => [:create, :new, :show, :edit, :update]

  resources :groups do
    resources :contents, :only => [:index, :create, :new]
  end

  resources :contents, :only => [:index, :show, :edit, :update, :destroy]

  resources :images, :only => [:create, :show, :update, :delete]

end

app/models/content.rb
class Content < ActiveRecord::Base
  belongs_to :group
  has_many :images, as: :imageable
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :contents
  belongs_to :site
  has_many :images, as: :imageable
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :imageable, :polymorphic => true
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :user
  has_many :groups
  has_many :images, as: :imageable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :site
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController

  def index
  end

  def create
    @group = Group.find(params[:group_id])
    @content = Content.new(content_params)
    @content.group_id = @group.id
    @content.save
    redirect_to '/admin'
  end

  def new
    @group = Group.find(params[:group_id])
    @content = Content.new
  end

  def show
    @content = Content.find(params[:id])
  end

  def edit
    @content = Content.find(params[:id])
    @group = Group.find(@content.group_id)
  end

  def update
    @content = Content.find(params[:id])
    if content_params["featured"] == nil
      @content.featured = false
      @content.save
    end
    @content.update(content_params)
  end

  def destroy
    @content = Content.find(params[:id])
    @content.destroy
    redirect_to '/admin'
  end

  private

  def content_params
    params.require(:content).permit(:title, :subtitle, :story, :featured)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end

  def create
    @site = Site.find_by(user_id: current_user.id)
    @group = Group.new(group_params)
    @group.site_id = @site.id
    @group.save
    redirect_to '/admin'
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
    @contents = Content.where(group_id: @group.id)
  end

  def update
    @group = Group.find(params[:id])
    if group_params["nav"] == nil
      @group.nav = false
      @group.save
    end
    @group.update(group_params)
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to '/admin'
  end

  private

  def group_params
    params.require(:group).permit(:name, :nav)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def create
    @image = Image.new
    @site = Site.first
    @image.imageable_type = params["image"]["imageable_type"]
    @image.imageable_id = params["image"]["imageable_id"]
    @image.data = File.read(params["picture"].tempfile)
    @image.save
    redirect_to '/admin'
  end

  def show
    @image = Image.find(params[:id])
    send_data @image.data, filename: "site_logo.jpg", type: "image/jpeg", disposition: "inline"
  end

  def update
    @image = Image.find_by(imageable_type: params["image"]["imageable_type"], imageable_id: params["image"]["imageable_id"])
    @image.data = File.read(params["picture"].tempfile)
    @image.save
    redirect_to '/admin'
  end

  def delete
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    "/admin"
  end

  def after_inactive_sign_up_path_for(resource)
    "/admin"
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController

  def index
    @site = Site.all.first
    if @site != nil
      @groups = Group.where(site_id: @site.id)
      @contents = []
      @groups.each do |group|
        @contents << Content.where(group_id: group.id)
        @contents.flatten!
      end
      @logo = Image.find_by(imageable_type: "site", imageable_id: @site.id)
    else
      redirect_to '/admin'
    end
  end

  def create
    @site = Site.new(site_params)
    @site.user_id = current_user.id
    @site.save
    redirect_to '/admin'
  end

  def new
    @site = Site.new
  end

  def edit
  end

  def show
    @site = Site.find_by(user_id: current_user.id)
    @groups = @site.groups
  end

  def update
    @site = Site.find_by(user_id: current_user.id)
    @site.update(site_params)
  end

  private

  def site_params
    params.require(:site).permit(:name, :headline)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @site = Site.find_by(user_id: current_user.id)
    if @site != nil
      @groups = @site.groups
      @logo = Image.find_by(imageable_type: "site", imageable_id: @site.id)
        # binding.pry
      # if @logo != nil
        # new_image = File.new(Rails.root.join("public/assets/images/logo.jpg"), "w") images_controller:
        # new_image.syswrite(@logo.data)
        # new_image.close
      # end
    else
      redirect_to '/site/new'
    end
  end

  def new
  end

  def create
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contents/edit.html.erb
<%= link_to "Admin","/admin" %>
<%= link_to "Edit #{@group.name}","/groups/#{@group.id}/edit" %>

<div class="edit-content">

  <%= form_tag "/contents/#{@content.id}", method: :put do %>

    <div class="edit-content-title">
      <%= label_tag "content[title]", "Title:" %><br/>
      <%= text_field_tag "content[title]", "#{@content.title}" %>
    </div>

    <div class="edit-content-subtitle">
      <%= label_tag "content[subtitle]", "Subtitle:" %><br/>
      <%= text_field_tag "content[subtitle]", "#{@content.subtitle}" %>
    </div>

    <div class="edit-content-image">
      <%= label_tag "content[image]", "Image:" %><br/>
      <%= file_field_tag "content[image]" %>
    </div>

    <div class="edit-content-story">
      <%= label_tag "content[story]", "Story:" %><br/>
      <%= text_area_tag "content[story]", "#{@content.story}" %>
    </div>

    <div class="edit-content-featured">
      <%= label_tag "content[featured]", "Featured:" %><br/>
      <% if @content.featured %>
        <input checked="checked" id="content[featured]" name="content[featured]" type="checkbox" /><!-- Went around form helpers because value was changing with "checked" -->
      <% else %>
        <%= check_box_tag "content[featured]" %>
      <% end %>
    </div>

    <div class="edit-content-submit">
      <%= submit_tag "Submit Content" %>
    </div>

  <% end %>

</div>

app/views/contents/new.html.erb
<div class="new-content">

  <%= form_tag "/groups/#{@group.id}/contents", method: :post do %>

    <div class="new-content-title">
      <%= label_tag "content[title]", "Title:" %><br/>
      <%= text_field_tag "content[title]" %>
    </div>

    <div class="new-content-subtitle">
      <%= label_tag "content[subtitle]", "Subtitle:" %><br/>
      <%= text_field_tag "content[subtitle]" %>
    </div>

    <div class="new-content-image">
      <%= label_tag "content[image]", "Image:" %><br/>
      <%= file_field_tag "content[image]" %>
    </div>

    <div class="new-content-story">
      <%= label_tag "content[story]", "Story:" %><br/>
      <%= text_area_tag "content[story]" %>
    </div>

    <div class="new-content-featured">
      <%= label_tag "content[featured]", "Featured:" %><br/>
      <%= check_box_tag "content[featured]" %>
    </div>

    <div class="new-content-submit">
      <%= submit_tag "Submit Content" %>
    </div>

  <% end %>

</div>

app/views/contents/show.html.erb
<%= stylesheet_link_tag 'reset', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'newspaper', 'data-turbolinks-track' => true %>


     <nav class='navbar clear'>
      <%= link_to root_path do %> <div class='nav-brand'><%= @content.group.site.name %></div><% end %>
      <div class='nav-links'>
        <ul>
        <% @content.group.site.groups.reverse.each do |x| %>
          <% if x.nav = true %>
          <li>
            <%= link_to x.name,group_path(x.id)%> 
          </li>
          <% end %>
        <% end %>
        </ul>
      </div>
    </nav>

<section class='page-container content'>
<h1><%= @content.title %></h1>
<% if @content.images.first.nil? %>
  <img src='http://placehold.it/800x300&text=No+Image+Found'>
<% else %>
  <%= image_tag '/images/#{@content.images.first.id}' %>
<% end %>
<h2><%= @content.subtitle %></h2>
<h3><%= @content.created_at %></h3>
<p><%= simple_format(@content.story)%></p>
</section>

app/views/contents/update.js.erb
$('.edit-content-submit-button').blur();
$('.edit-content-request').empty()
$('.edit-content-request').append('<p class="content-request-text">Content successfully updated.</p>')

app/views/groups/edit.html.erb
<%= link_to "Admin","/admin" %>

<div class="edit-group">
  <%= form_tag "/groups/#{@group.id}", method: :put do %>

    <div class="edit-group-name">
      <%= label_tag "group[name]", "Name:" %>
      <%= text_field_tag "group[name]", "#{@group.name}" %>
    </div>

    <div class="edit-group-nav">
      <%= label_tag "group[nav]", "In the Navbar:" %>
      <% if @group.nav %>
        <input checked="checked" id="group[nav]" name="group[nav]" type="checkbox" /><!-- Went around form helpers because value was changing with "checked" -->
      <% else %>
        <%= check_box_tag "group[nav]" %>
      <% end %>
    </div>

    <div class="edit-group-submit">
      <%= submit_tag "Submit" %>    
    </div>

  <% end %>

  <h3>Contents</h3>
  <div class="content-create">
    <%= link_to "Create Content","/groups/#{@group.id}/contents/new" %>
  </div>
  <ol>
    <% @contents.each do |content| %>
      <li>
        <%= link_to "Edit #{content.title}", "/contents/#{content.id}/edit" %>
      </li>
    <% end %>

</div>

app/views/groups/new.html.erb
<div class="new-group">

  <%= form_tag "/groups", method: :post do %>

    <div class="new-group-name">
      <%= label_tag "group[name]", "Name:" %>
      <%= text_field_tag "group[name]" %>
    </div>

    <div class="new-group-nav">
      <%= label_tag "group[nav]", "In the Navbar:" %>
      <%= check_box_tag "group[nav]" %>
    </div>

    <div class="new-group-submit">
      <%= submit_tag "Submit" %>
    </div>

  <% end %>

</div>

app/views/groups/new.js.erb
// $('#new-group-form').html("<%= j (render 'newgroupform') %>");
// $('#new-group-form').slideDown(350);

app/views/groups/show.html.erb
<%= stylesheet_link_tag 'reset', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'newspaper', 'data-turbolinks-track' => true %>


     <nav class='navbar clear'>
            <%= link_to root_path do %> <div class='nav-brand'><%= @group.site.name %></div><% end %>
      <div class='nav-links'>
        <ul>
        <% @group.site.groups.reverse.each do |x| %>
          <% if x.nav = true %>
          <li>
            <%= link_to x.name,group_path(x.id)%> 
          </li>
          <% end %>
        <% end %>
        </ul>
      </div>
    </nav>

    <section class='page-container clear'>
      <% if @group.images.first.nil? %>
        <img src='http://placehold.it/800x150&text=No+Image+Found'>
      <% else %>
        <%= image_tag '/images/#{@groups.images.first.id}' %>
      <% end %>
      <% @group.contents.reverse.each do |x| %>
        <% if x.featured == true %>
      <%= link_to content_path(x.id) do%>
      <article class='featured-post clear'>
      <% if Image.where(imageable_type: x.class.to_s.downcase, imageable_id: x.id).nil? %>
        <img src='http://placehold.it/800x150&text=No+Image+Found'>
      <% else %>
        <%= image_tag "/images/#{x.id}.jpg" %>
        <h2><%= x.title %></h2>
        <h4><%= x.subtitle%></h4>
        <p><%= simple_format(x.story.split(' ').slice(0, 50).join(' ')+'...')%></p>
      </article>
      <% end %>
      <% end %>
      <% end %>
      <% @group.contents.reverse.each do |x| %>
        <% if x.featured == false %>
      <%= link_to content_path(x.id) do%>
      <article class='article-link clear'>
      <% if Image.where(imageable_type: x.class.to_s.downcase, imageable_id: x.id).nil? %>
        <img src='http://placehold.it/800x150&text=No+Image+Found'>
      <% else %>
        <%= image_tag "/images/#{x.id}.jpg" %>
        <div class='content'>
        <h2><%= x.title %></h2>
        <h4><%= x.subtitle%></h4><p><%= simple_format(x.story.split(' ').slice(0, 50).join(' ')+'...')%></p><p><%= x.story.split(' ').slice(0, 50).join(' ') %>...</p>
        </div>
      </article>
      <% end %>
      <% end %>
      <% end %>
    </section>

app/views/groups/update.js.erb
$('.edit-group-submit-button').blur();
$('.edit-group-request').empty()
$('.edit-group-request').append('<p class="content-request-text">Group successfully updated.</p>')

app/views/groups/xnew.html.erb
<div class="new-group">

  <%= form_tag "/groups", method: :post do %>

    <div class="new-group-name">
      <%= label_tag "group[name]", "Name:" %>
      <%= text_field_tag "group[name]" %>
    </div>

    <div class="new-group-nav">
      <%= label_tag "group[nav]", "In the Navbar:" %>
      <%= check_box_tag "group[nav]" %>
    </div>

    <div class="new-group-submit">
      <%= submit_tag "Submit" %>
    </div>

  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jandr</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/sitelayout.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title></title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="reset.css">
        <link rel="stylesheet" href="newspaper.css">
    <body>

     <nav class='navbar clear'>
      <div class='nav-brand'><%= @site.name %></div>
      <div class='nav-links'>
        <ul>
        <%= @groups.each do |x| %>
          <% if x.nav = true %>
          <li>
            <%= link_to x.name,group_path(x.id)%> 
          </li>
          <% end %>
        <% end %>
        </ul>
      </div>
    </nav>

<% yield %>

  </body>
</html>

app/views/site/index.html.erb
<body>

<%= stylesheet_link_tag 'reset', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'portfolio', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'color-scheme-1', 'data-turbolinks-track' => true %>

     <nav class='navbar clear'>
            <%= link_to root_path do %> <div class='nav-brand'><%= @site.name %></div><% end %>
      <div class='nav-links'>
        <ul>
        <% @groups.reverse.each do |x| %>
          <% if x.nav = true %>
          <li>
            <%= link_to x.name,group_path(x.id)%>
          </li>
          <% end %>
        <% end %>
        </ul>
      </div>
    </nav>

    <section class='page-container'>
      <% if Image.where(imageable_type: @groups.last.class.to_s.downcase, imageable_id: @groups.last.contents.first.id).nil? %>
        <img src='http://placehold.it/800x150&text=No+Image+Found'>
      <% else %>
        <%= image_tag '/images/1.jpg' %>
      <% end %>
      <% @groups.last.contents.reverse.each do |x| %>
        <% if x.featured == true %>
      <%= link_to content_path(x.id) do%>
      <article class='featured-post clear'>
      <% if Image.where(imageable_type: x.class.to_s.downcase, imageable_id: x.id).nil? %>
        <img src='http://placehold.it/800x150&text=No+Image+Found'>
      <% else %>
        <%= image_tag "/images/#{x.id}.jpg" %>
      <% end %>
        <h2><%= x.title %></h2>
        <h4><%= x.subtitle%></h4>
        <p><%= x.created_at %></p>
        <p><%= simple_format(x.story.split(' ').slice(0, 50).join(' ')+'...')%></p>
      </article>
      <% end %>
      <% end %>
      <% end %>
      <% @groups.last.contents.reverse.each do |x| %>
        <% if x.featured == false %>
      <%= link_to content_path(x.id) do%>
      <article class='article-link clear'>
      <% if Image.where(imageable_type: x.class.to_s.downcase, imageable_id: x.id).nil? %>
        <img src='http://placehold.it/800x150&text=No+Image+Found'>
      <% else %>
        <%= image_tag "/images/#{x.id}.jpg" %>
      <% end %>
        <h2><%= x.title %></h2>
        <h4><%= x.subtitle%></h4>
        <p><%= x.created_at %></p>
        <p><%= simple_format(x.story.split(' ').slice(0, 50).join(' ')+'...') %></p>
      </article>
      <% end %>
      <% end %>
      <% end %>
    </section>

  </body>
</html>

app/views/site/new.html.erb
<%= form_tag "/site", method: :post do %>

  <div class="site-name">
    <%= label_tag "site[name]", "Name:" %><br/>
    <%= text_field_tag "site[name]"%>
  </div>

  <div class="site-headline">
    <%= label_tag "site[headline]", "Headline:" %><br/>
    <%= text_field_tag "site[headline]" %>
  </div>

  <div class="site-logo">
    <%= label_tag "site[logo]", "Logo:" %><br/>
    <%= file_field_tag "site[logo]" %>
  </div>

  <div class="site-theme">
    <%#= label_tag "site[theme]", "Theme:" %><br/>
    <%#= select_tag "site[theme]", options_for_select(@themes, "id", "name") %>
  </div>


  <%= submit_tag "Submit" %>

<% end %>

app/views/site/update.js.erb
$('.submit').blur();
$('.edit-site-request').empty();
$('.edit-site-request').append('<p class="request-text">Site successfully updated.</p>');